services:
  togetherjs_server:
    container_name: togetherjs-server-${ENVIRONMENT}
    image: ghcr.io/ut-bms-ist/togetherjs-server:${TOGETHERJS_TAG:-latest}
#    build:
#      context: ./
#      dockerfile: 'Dockerfile'
    restart: unless-stopped
    ports:
      - "${PORT}:443"
    environment:
      - HUB_SERVER_HOST=togetherjs_server
      - HUB_SERVER_PORT=443
      - LOG_LEVEL=${LOG_LEVEL}
      - STDOUT=${STDOUT}
      - HTTPS=${HTTPS}

