# Usage: docker-compose -f docker-compose-image-from-ghcr.yml up -d
# This will start the togetherjs-server container from the image ghcr.io/ut-bms-ist/togetherjs-server:latest
version: "3"

services:
  togetherjs_server:
    container_name: togetherjs-server-${ENVIRONMENT}
    image: ghcr.io/ut-bms-ist/togetherjs-server:latest
    restart: unless-stopped
    ports:
      - "${PORT}:443"
    environment:
      - HUB_SERVER_HOST=togetherjs_server
      - HUB_SERVER_PORT=443
      - LOG_LEVEL=${LOG_LEVEL}
      - STDOUT=${STDOUT}
      - HTTPS=${HTTPS}
